### ISSUE TITLE
无法支持pandoc解析

### ISSUE THREAD

**Issue by panlei7** [zthxxx/hexo-theme-Wikitten#10]
我写公式的时候发现下划线解析错误，然后网上查到解决方法，见[Hexo下mathjax的转义问题](http://shomy.top/2016/10/22/hexo-markdown-mathjax/)。我按照第三种方式更换markdown引擎，之后发现无法解析公式了。我换成另两个主题yilia和yelee，可以解析。是这个主题不支持吗？

**Comment by panlei7** [comment]
我不会js，完全是按照其他theme照搬过来，只能说结果是好的。 #11

**Comment by zthxxx** [comment]
能不能详细说明下是所有 `mathjax` 公式都无法渲染，还是部分公式因为转义而渲染出错？

**Comment by zthxxx** [comment]
这个主题设计的是有 `LaTex` 公式渲染的，其渲染效果可见我自己的 wiki 站点中：
[带公式渲染的示例](https://wiki.zthxxx.me/wiki/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86/%E5%9B%BE%E5%BD%A2%E5%9B%BE%E5%83%8F/%E6%9B%B2%E7%BA%BF%E8%B0%83%E6%95%B4%E5%B7%A5%E5%85%B7/#「曲线工具」)
我猜测你开始的原因是缺少插件，`LaTex` 的渲染需要安装 Hexo 插件，`hexo-math`，这在文档 README 中写得有：
[README-插件](https://github.com/zthxxx/hexo-theme-Wikitten/blob/master/README_zh-CN.md#安装)
> 需要安装的插件写在主题的 package.json 文件中。
> ......
> "hexo-math": "^3.0.2"	// 渲染 LaTex 公式
> ......
> $ npm install --save hexo-math

**Comment by panlei7** [comment]
是部分公式，我第一个帖子中给的那个链接，里面提到我遇到的下划线问题。然后我尝试使用链接中第三种方法，使用hexo-renderer-pandoc，但发现公式完全没有渲染。我就按照其他theme中的设置，添加了mathjax.ejs，现在渲染正确了。

**Comment by zthxxx** [comment]
`hexo-math` 插件也是插入标签加载 `MathJax.js`，跟你提的 PR 相同，部分公式的解析错误可以尝试去 [`hexo-math` 的项目](https://github.com/hexojs/hexo-math/) 里提提 Issue，不过你现在已经靠自己的努力解决问题了，就按照你自己的办法使用也是挺好的。
