### ISSUE TITLE
请问你这个在首页按分类输出文章是怎么做的？

### ISSUE THREAD

**Issue by QingShui23** [zthxxx/hexo-theme-Wikitten#17]
我最近想写一个主题，根据在首页显示分类，然后展示分类文章。

**Comment by zthxxx** [comment]
如果你问的是左侧的侧边栏中的分类显示的话，大概是这个文件中的这一段

https://github.com/zthxxx/hexo-theme-Wikitten/blob/master/layout/widget/category.ejs#L94-L95

但这个侧边栏不只是在首页显示，在所有页面的侧边都会显示；如果你只是想在首页显示，那可以在这个文件还是这两行前面加一个判断时候首页，或者把逻辑提出来你自己重写。

**Comment by QingShui23** [comment]
我昨天自己看了一下，发现实现步骤略微有些麻烦，不知道有没有更简单的方式可以实现这个功能？

**Comment by zthxxx** [comment]
我又重看了遍我的代码，确实设计得不好，实现比较麻烦和混乱，也可能跟当时 Hexo api 的限制有关，现在新版本 Hexo 下我不知道有没有更好的实现方式。

之前的大致思路是，分别遍历 `site.categories` 和 `site.posts`，提取出分类对应的文章数据再组合出一个 这样的 `category` 对象
```js
category = { 
  _id: String, 
  name: String,
  articles: Array<post>, 
  children: Array<category> 
}
```
作为数据对象，用于后面渲染 html，
主要复杂的地方在遍历构建  `category` 对象的过程，
如果你发现更优雅的实现方式，欢迎提个 PR
