### ISSUE TITLE
关于多级分类的疑问

### ISSUE THREAD

**Issue by daikerSec** [zthxxx/hexo-theme-Wikitten#24]
你好，我想问下多级分类怎么实现，我通过`category`来实现分类不是很难，但是怎么实现多级分类

**Comment by zthxxx** [comment]
建议先读文档，

https://hexo.io/docs/front-matter.html#Categories-amp-Tags

多级分类是 Hexo 在 Front-matter 中定义的，主题只负责样式，
这个问题与主题无关
