### ISSUE TITLE
把categories archives等改成英文后出现问题

### ISSUE THREAD

**Issue by yu-zou** [zthxxx/hexo-theme-Wikitten#26]
首先非常感谢您的分享，非常喜欢您这个hexo主题。但是我在使用的时候，由于本人需要写英文博客，所以把归档，标签这些中文字都改成了英文比如archives,tags。但是在显示的时候，有时候显示正常，但是偶尔会显示出一些似乎像英文但是又不太像的英文单词，比如categorias, archivos，等等，而且在hexo server上看是正常的，deploy到github上才出问题。比如像这样：
![image](https://user-images.githubusercontent.com/11840520/41506295-13087598-71e9-11e8-9712-c4ce3e0d700c.png)
请问这有可能是什么问题造成的呢？谢谢

**Comment by zthxxx** [comment]
看了你的博客仓库，没有找到原因，
虽然觉得不太可能，但是基于获取到的信息用排除法用，还是想问下是不是只是你打错字了，
本地不用 server，直接 build 再启一个静态服务器试试 (比如 python -m http.server)

另外，改语言的话，应该也是不用你亲自改文字的，本主题提供得有多语言(根据 icarus 来的)选项
https://github.com/zthxxx/hexo-theme-Wikitten/blob/master/languages/en.yml

**Comment by yu-zou** [comment]
好的，谢谢啦。应该不是我打错了的问题，哈哈哈。我有的时候稍微改动一些文章，然后重新编译再提交上去就会出现不是英文的现象，大部分时候不会出现，可能是我配置有些问题，我再去check以下。多谢及时回复。

**Comment by chendi20082009** [comment]
> 好的，谢谢啦。应该不是我打错了的问题，哈哈哈。我有的时候稍微改动一些文章，然后重新编译再提交上去就会出现不是英文的现象，大部分时候不会出现，可能是我配置有些问题，我再去check以下。多谢及时回复。

一定把hexo的语言改成中文或者英文,我也遇到这种情况,就是这么解决的.

**Comment by reycn** [comment]
> 首先非常感谢您的分享，非常喜欢您这个hexo主题。但是我在使用的时候，由于本人需要写英文博客，所以把归档，标签这些中文字都改成了英文比如archives,tags。但是在显示的时候，有时候显示正常，但是偶尔会显示出一些似乎像英文但是又不太像的英文单词，比如categorias, archivos，等等，而且在hexo server上看是正常的，deploy到github上才出问题。比如像这样：
> ![image](https://user-images.githubusercontent.com/11840520/41506295-13087598-71e9-11e8-9712-c4ce3e0d700c.png)
> 请问这有可能是什么问题造成的呢？谢谢

Hexo 配置文件 _config.yml 中，`language` 应当为 `zh-Hans`
