### ISSUE TITLE
这个主题太赞了，能再做一个hugo版本的吗？

### ISSUE THREAD

**Issue by charliewin** [zthxxx/hexo-theme-Wikitten#28]
这个主题太赞了，能再做一个hugo版本的吗，我换hugo了，由于博文太多，用hexo生成太慢了，不得已换成hugo，发现还挺好用。

Hugo: https://gohugo.io/
Hugo: The world's fastest framework for building websites

**Comment by zthxxx** [comment]
不。。。不会这个啊，hugo 好复杂啊

**Comment by charliewin** [comment]
嗯嗯，zthxxx 你继续维护这个主题，等我学成前端，我自己port一个，到时候再联系你。
