### ISSUE TITLE
如何禁用 sitemap

### ISSUE THREAD

**Issue by charliewin** [zthxxx/hexo-theme-Wikitten#29]
我试两种方法，最后 sitemap 还是会生成：
1. 将 sitemap 注释掉
2. 在 sitemap 里面加上 enable: false

如何才能让 sitemap 不生成？

我的博文比较多，生成太花时间了，想减少一些插件上的负担以减少生成时间 @_@

**Comment by zthxxx** [comment]
直接删掉 hexo-generator-sitemap 这个插件就好。。。

为什么不读读神奇的文档呢  https://github.com/hexojs/hexo-generator-sitemap
