### ISSUE TITLE
我执行 hexo generate 爆内存怎么办

### ISSUE THREAD

**Issue by charliewin** [zthxxx/hexo-theme-Wikitten#30]
我执行 hexo generate 过个几分钟，就会报出错误：FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory。

hexo-cli 加了参数 --max_old_space_size=8192 后还是会报。

我的博客 md 文档数大概 200 个左右，怎么办？

**Comment by zthxxx** [comment]
你的机子型号内存？
据我了解的，200 左右不算能撑爆 8G 的量，再说还有 swap 空间，
大概应该是 node 对内存占用的限制，V8 提供两个内存配置项
--max-old-space-size
--max-new-space-size
你应该试试

**Comment by zthxxx** [comment]
加油，相信你可以改一个好看的 hugo 主题出来用的
