### ISSUE TITLE
几个小问题求助

### ISSUE THREAD

**Issue by chendi20082009** [zthxxx/hexo-theme-Wikitten#31]

**Comment by chendi20082009** [comment]
1. 这个搜索框的文字为什么是个法语词（Rechercher），如何修改呢？
![image](https://user-images.githubusercontent.com/10103354/43813983-b0bf641a-9afa-11e8-981c-0eb5ed7f891c.png)
2. 已经fa防止网站图标文件，但是就是显示不出来，该怎么办呢？
![image](https://user-images.githubusercontent.com/10103354/43814015-dac2f3f8-9afa-11e8-87de-bc076e597cd9.png)
![image](https://user-images.githubusercontent.com/10103354/43814029-ecc7ed60-9afa-11e8-9ad4-6e95722378f7.png)

**Comment by chendi20082009** [comment]
第一个问题已经解决，把根目录下_config.yml的语言修改成中文的即可。
![image](https://user-images.githubusercontent.com/10103354/43814206-b2740b02-9afb-11e8-870d-2bfd185e1101.png)

**Comment by chendi20082009** [comment]
第一个问题已经解决，把_config.yml的语言修改成中文的即可
![image](https://user-images.githubusercontent.com/10103354/43814646-fca42764-9afd-11e8-86d5-b99d535c39b0.png)

**Comment by zthxxx** [comment]
直接访问 '/favicon.ico' 如果响应图片正常，那就没问题，只是 chrome 缓存问题，
清一下缓存再重启 chrome 试试

**Comment by chendi20082009** [comment]
非常感谢，果然是浏览器缓存的问题！
PS：你制作的主题以及写的 [用 Hexo 做个人 Wiki 知识管理系统](https://www.v2ex.com/t/347176?p=1) 很赞！很受用！
顺便也与你分享下我使用的的工具：
1. 有道云笔记用于收集与快速记录。
2. 基于hexo 和Wikitten主题的wiki。
3. 基于confluence的知识系统，也是类wiki的。（最早是采用的confluence server，由于并不懂代码，连linux都不懂，经常出现问题不知道如何解决，最后选择了confluence cloud，一年100$）

**Comment by chendi20082009** [comment]
我的个人wiki，初步整好，开始写点东西~
https://wiki.chendi.org/

**Comment by chendi20082009** [comment]
另外，再请教一个问题，如何像你的wiki似的，网站首页固定为某一个page 或post，而不是最新文章呢？

**Comment by zthxxx** [comment]
Readme 里面有关于首页的描述

**Comment by chendi20082009** [comment]
谢谢已经搞定：
第一步：在source文件夹下新建index.md
第二步：主题目录下default_index_file: index.md
第三步：删除node_modules文件夹下的hexo-generator-index文件夹
