### ISSUE TITLE
是否考虑在 Hugo 下做一个类似的主题吗，很想用这个主题，但是 hexo 处理 2000 文章时要几个小时，Hugo 几十秒

### ISSUE THREAD

**Issue by iterateself** [zthxxx/hexo-theme-Wikitten#33]
在hexo下用过这个主题，但是hexo本身有{{}}和{%%}导致的内容泄露的问题，而且，超1000文章的时候，速度非常慢。Hugo 几十秒就可以。
因此转到了Hugo，暂时用的even主题。

**Comment by iterateself** [comment]
嗯，hugo 2000 不是十几秒，几十秒吧。

**Comment by zthxxx** [comment]
不好意思了，这个暂时没打算🌚
