### ISSUE TITLE
大神您好，上传的文件显示的时候是按照什么顺序显示的呢？列表显示的是标题而不是文件名字是正常现象吗

### ISSUE THREAD

**Issue by listwebit** [zthxxx/hexo-theme-Wikitten#34]

**Comment by listwebit** [comment]
比如我上传了三个文件：
1.划分聚类法之k-means
2.密度聚类法之DBSCAN
3.层次聚类法之CANOPY
实际排序效果是：
1.划分聚类法之k-means
3.层次聚类法之CANOPY
2.密度聚类法之DBSCAN

而且显示的名字是根据内容中的title来显示的，能不能根据文件名字显示呢？

谢谢回答

**Comment by zthxxx** [comment]
确实是按标题名排序的，以前的 issue 里写过介绍和原因

#9 

文章排序是用的官方的实现，对 hexo 渲染来说，拿到的是文章内容，而不是文件名 (虽然能拿到)，
所以做的是关于内容的排序 不是关于文件本身的排序

[hexojs/hexo-generator-index](https://github.com/hexojs/hexo-generator-index)

如果你的标题也是  1.划分...  2.密度...  3.层次...

最后排序却是 1. 3. 2.   那么就是有问题的，请再回复我
