### ISSUE TITLE
markdown 的引用样式错乱

### ISSUE THREAD

**Issue by Norcy** [zthxxx/hexo-theme-Wikitten#35]
![image](https://user-images.githubusercontent.com/8423011/47717727-84b2c380-dc81-11e8-9555-0563a1a20a39.png)

**Comment by zthxxx** [comment]
多提供些信息，复现 markdown 源码也发一下

**Comment by Norcy** [comment]
https://norcy.github.io/wiki/%E5%BA%93/%E5%BA%93%E4%BD%93%E7%A7%AF%E4%BC%98%E5%8C%96/

https://github.com/Norcy/wiki/blob/HexoBackup/source/_posts/%E5%BA%93/%E5%BA%93%E4%BD%93%E7%A7%AF%E4%BC%98%E5%8C%96.md

**Comment by zthxxx** [comment]
两张截图：

---------

![image](https://user-images.githubusercontent.com/15135943/51816324-ff32c400-2300-11e9-88a7-eab322f33e10.png)

![image](https://user-images.githubusercontent.com/15135943/51816337-15d91b00-2301-11e9-80c0-a54fe3ddeb6d.png)

---------

显然是你源码 markdown 语法写错了啊，

光是 GitHub editor 给你的预览不对了。。。

看下下面这个

> <起始地址> <结束地址> <函数> [<文件名:行号>]

**Comment by Norcy** [comment]
oh 好的，看起来是我的markdown客户端做兼容了。不好意思哈

**Comment by zthxxx** [comment]
建议先读一下 Markdown 语法，评论栏左下角就有 GitHub 官方 GFM 文档和基础语法

https://guides.github.com/features/mastering-markdown/#syntax
