### ISSUE TITLE
左边导航栏的标题是空的

### ISSUE THREAD

**Issue by Norcy** [zthxxx/hexo-theme-Wikitten#36]
发现 .md 文件的内容一定要写 
```
---
title: xxx
```
```

不然就会出现标题是空的情况，能不能用文件名来代替呢

**Comment by zthxxx** [comment]
https://hexo.io/zh-cn/docs/front-matter

`title` 一定要写，也应该必须指定； 

文件名和标题从各个角度来说都完全不一样，
标题是代表文章的，
文件名是作用在 url 上，应该遵循 `spinal-case` 命名规范，更不应该有中文或者空格

**Comment by Norcy** [comment]
> https://hexo.io/zh-cn/docs/front-matter
> 
> `title` 一定要写，也应该必须指定；
> 
> 文件名和标题从各个角度来说都完全不一样，
> 标题是代表文章的，
> 文件名是作用在 url 上，应该遵循 `spinal-case` 命名规范，更不应该有中文或者空格

嗯，刚也发现了。关于 `spinal-case` 这个学习了。谢谢哈

**Comment by zthxxx** [comment]
感谢你的使用和反馈
