### ISSUE TITLE
文章的排序

### ISSUE THREAD

**Issue by Layty** [zthxxx/hexo-theme-Wikitten#38]
我看到有说是按照 内容标题排序，但是我的比较奇怪，不知道按照什么排序的
![image](https://user-images.githubusercontent.com/14368090/49772196-4d770e00-fd27-11e8-8a81-eb51fa4b29d7.png)

**Comment by Layty** [comment]
https://layty.gitee.io/ 这是博客的地址

**Comment by zthxxx** [comment]
see #9

按文件名排序，自动识别前缀数字

因为不加插件的情况下，Hexo 不能按 front matter 排序

**Comment by Layty** [comment]
![image](https://user-images.githubusercontent.com/14368090/49773546-85348480-fd2c-11e8-87f4-f042a0d8c2b1.png)
我的文件名是有这个排序的啊  01-，02-，。。。。。等等的

**Comment by zthxxx** [comment]
源码在哪儿呢， gitee 上我没有找到你的仓库

**Comment by Layty** [comment]
https://gitee.com/layty/Layty  文章在这里

**Comment by zthxxx** [comment]
1. 文件名前面的 0 影响了 hexo 读取文件的顺序
2. 发现是严格按照文件名字符顺序比较的，没有加识别数字前缀 (明明记得有。。~~错觉~~)
3. 要不你可以试试 index 排序插件

https://github.com/hexojs/hexo-generator-index

**Comment by Layty** [comment]
刚刚更新了那个插件， 发现还是有一个文章排序不对，暂时先改下文件名。
等待作者大大啥时候有空更新吧，反正博客就是给自己看的，不讲究了。哈哈哈哈

**Comment by zthxxx** [comment]
感谢反馈，我有空再修复一下

**Comment by Layty** [comment]
好的，我刚发现你之前的截图有点小问题 
![image](https://user-images.githubusercontent.com/14368090/49776078-9a61e100-fd35-11e8-8526-9f38ea2e728a.png)

**Comment by zthxxx** [comment]
> 2. 发现是严格按照文件名字符顺序比较的，没有加识别数字前缀

大概是 hexo 按字符顺序读取文件的原因，数字 ascii 比 `-` 小，`0` 放最后了
