### ISSUE TITLE
是否支持根据Markdown文件所在目录层级自动分类？

### ISSUE THREAD

**Issue by himao** [zthxxx/hexo-theme-Wikitten#4]
目前分类是在Markdown文档填写`categories`字段来实现的。为了便于管理Markdown文件在本地使用了简单的目录进行分类，不知能否根据本地目录层级生成静态文件的分类，省去手写麻烦，避免出错，和本地目录层级不匹配的问题。

**Comment by zthxxx** [comment]
暂时不支持，Hexo 目前都是在 `Front-matter` 中填写 `categories` 字段来作分类的，很少有人有需要通过文件目录来分类的需求，目前有没有见过哪一个主题有这个功能；Hexo 提倡的是所有文章都放在 `_posts` 目录下，所以一般都这样做的。

如果此需求量大的话，可能会考虑添加此功能。

如果看到有哪个主题支持通过文件目录自动分类的，请在此处留言告诉我。

**Comment by himao** [comment]
Hexo主题的确没见过根据文件目录自动分类的。simiki可以根据目录生成静态文件，不过只有一级。docsify支持多级目录，不过要手动建立索引。  
之所以对Markdown文档进行目录管理，是认为wiki“裸数据”（原始数据，即Markdown文档）的可读性和可维护性比较重要，即不借助其他程序，wiki数据在本地仍是可以方便的查找使用的。这样后期不管是更换wiki程序，还是直接把目录结构放到GitHub上，灵活性都大了不少。  
当然，目前的主题已能满足以上需求，只是需要手动填写`categories`字段略麻烦些。

**Comment by zthxxx** [comment]
I have add this feature.
To see: 
https://github.com/zthxxx/hexo-directory-category#readme
https://github.com/zthxxx/hexo-theme-Wikitten/blob/cdd521d7452187f349f094a0420bede91a6fcd7a/README_zh-CN.md#安装说明
https://github.com/zthxxx/Wiki-site/commit/dca2825e0a415bcb75d23fd59ec06be5a1c12670

**Comment by himao** [comment]
@zthxxx 非常感谢你的工作！

**Comment by zthxxx** [comment]
@himao   oh, U are welcome!

**Comment by chendi20082009** [comment]
@zthxxx 感谢,这个功能很赞!
