### ISSUE TITLE
Some problem with mathjax

### ISSUE THREAD

**Issue by JackieAnxis** [zthxxx/hexo-theme-Wikitten#40]
When I used the mathjax to render the formula, the problem appeared.
The formula I wrote was:
${\hat{\varepsilon}}_s(h_\theta)$

it cannot be rendered because of the `_` character. When I changed it to 
${\hat{\varepsilon}_s}(h_\theta)$

It worked. So do you have any idea of that?

**Comment by zthxxx** [comment]
![image](https://user-images.githubusercontent.com/15135943/51248114-181aab80-19ca-11e9-9e30-3131a8905f87.png)
i see some diff, but these are not any `_` characters

**Comment by JackieAnxis** [comment]
Sorry, I missed it. The formula was: 
${\hat{\varepsilon}}_s(h\theta)$

**Comment by JackieAnxis** [comment]
I want to render it as:
![image](https://user-images.githubusercontent.com/19246028/51249493-6b8ef880-19ce-11e9-9cb1-d003bbbfeef0.png)

**Comment by JackieAnxis** [comment]
Thanks a lot, I've find the problem:
![image](https://user-images.githubusercontent.com/19246028/51290920-391de380-1a40-11e9-80ca-cf38586ef1e0.png)

**Comment by JackieAnxis** [comment]
hello, I've solved this problem by using another renderer:
`npm un hexo-renderer-marked --save`
`npm i hexo-renderer-kramed --save # or hexo-renderer-pandoc`
`hexo clean`
`hexo s`
Follow this instruction: https://github.com/hexojs/hexo/issues/3148#issuecomment-408418625

**Comment by JackieAnxis** [comment]
Quite awesome!
![image](https://user-images.githubusercontent.com/19246028/51422354-36f68900-1be8-11e9-8b7a-61de1aca67b0.png)

**Comment by zthxxx** [comment]
Perfect !

**Comment by zthxxx** [comment]
can you pr some code?

that's all your contribution

**Comment by JackieAnxis** [comment]
I'm sorry that this solution introduces other problems, I'll try to solve them and give more solutions.

**Comment by zthxxx** [comment]
Closed by pr #41
