### ISSUE TITLE
滑动卡顿

### ISSUE THREAD

**Issue by Norcy** [zthxxx/hexo-theme-Wikitten#45]
如果把 article 的宽度 auto 就不卡（效果上是 auto，可通过 display or width 来使宽度不被压缩）

以下是案发现场：

https://norcy.github.io/wiki/iOS/iOS%20%E5%9B%BE%E7%89%87%E5%8A%A0%E8%BD%BD%E7%9A%84%E5%9D%91/

**Comment by zthxxx** [comment]
有录屏 gif 🐎，我这儿丝般顺滑

**Comment by Norcy** [comment]
我最近自己改了很多样式，改来改去又没复现了。我下次遇到再来哈 谢谢你
