### ISSUE TITLE
缩进格式渲染错误

### ISSUE THREAD

**Issue by Norcy** [zthxxx/hexo-theme-Wikitten#46]
https://norcy.github.io/wiki/iOS/iOS%20%E5%9B%BE%E7%89%87%E5%8A%A0%E8%BD%BD%E7%9A%84%E5%9D%91/

![image](https://user-images.githubusercontent.com/8423011/61504798-38760200-aa0f-11e9-9f65-c2910ab9d786.png)

以下是原文

```
3. 关于 `@2x`/`@3x` 的坑

	假如现在有 image@2x.png 和 image@3x.png 2张图片
	
	以下代码可以正确找到图片，这种方法是直接寻找 image@2x.png
	
	```objc
	NSString *path = [[NSBundle mainBundle] pathForResource:@"image@2x" ofType:@"png"]; 
	UIImage *image = [UIImage imageWithContentsOfFile:path];
	```
	
	以下代码无法找到图片，这种方法是直接寻找 image.png
	
	```objc
	NSString *path = [[NSBundle mainBundle] pathForResource:@"image" ofType:@"png"]; 
	UIImage *image = [UIImage imageWithContentsOfFile:path];
	```
	
	以下代码可以正确找到图片，这种方法系统会帮助处理 `@2x`/`@3x`
	
	```objc
	NSString *path = [[[NSBundle mainBundle] resourcePath] stringByAppendingPathComponent:@"image.png"];
	UIImage *image = [UIImage imageWithContentsOfFile:path];
	```
```

**Comment by zthxxx** [comment]
空行不要有空格试试

---------------

一般的渲染缩进问题都是由于对 markdown 语法细节不清楚导致的，比如空格、换行、嵌套等

**Comment by zthxxx** [comment]
看了你的仓库，https://github.com/Norcy/wiki/ 
倒是把源码传上去啊喂

**Comment by xiongxiongzl** [comment]
弄的挺好，我不知道错在哪里了，渲染不出来，报错说是没有找到渲染文件

**Comment by zthxxx** [comment]
@xiongxiongzl 

兄弟，就算你这么说我也不知道你具体啥问题啊，

页面地址、源码地址倒是给一下呀

**Comment by Norcy** [comment]
> 看了你的仓库，https://github.com/Norcy/wiki/
> 倒是把源码传上去啊喂

你切个分支就能看到了~ HexoBackup

https://github.com/Norcy/wiki/blob/HexoBackup/source/_posts/iOS/iOS%20%E5%9B%BE%E7%89%87%E5%8A%A0%E8%BD%BD%E7%9A%84%E5%9D%91.md

**Comment by zthxxx** [comment]
> 空行不要有空格试试
> 
> 一般的渲染缩进问题都是由于对 markdown 语法细节不清楚导致的，比如空格、换行、嵌套等

看了你[新的源码](https://raw.githubusercontent.com/Norcy/wiki/HexoBackup/source/_posts/%E4%B8%8D%E5%8A%A1%E6%AD%A3%E4%B8%9A/iOS%20%E6%9C%AA%E5%88%86%E7%B1%BB/iOS%20%E5%9B%BE%E7%89%87%E5%8A%A0%E8%BD%BD%E7%9A%84%E5%9D%91.md)，换行后行首没有空格已经解决了这个缩紧问题，这个 issue 就先关掉了

![image](https://user-images.githubusercontent.com/15135943/82666037-91ce4380-9c67-11ea-876c-bfc72ac2e4ce.png)
