### ISSUE TITLE
default_index_file 报错，及 sidebar 生成问题

### ISSUE THREAD

**Issue by ValueInvestmentChina** [zthxxx/hexo-theme-Wikitten#49]
我更换您的主题，文件下载，config修改完毕，hexo -g，hexo -s都正常
但去localhost:4000去预览的时候报错，我是个小白，真的不知道咋回事，求帮助

Unhandled rejection TypeError: F:\hexo\themes\hexo-theme-Wikitten\layout\index.ejs:1
 >> 1| <%
    2| var indexArticle;
    3| var index_file = theme.customize.default_index_file;
    4| if(index_file) {

Cannot read property 'default_index_file' of undefined
    at eval (eval at compile (F:\hexo\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:11:34)
    at returnedFn (F:\hexo\node_modules\ejs\lib\ejs.js:668:17)
    at Theme._View.View._compiled.locals [as _compiled] (F:\hexo\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (F:\hexo\node_modules\hexo\lib\theme\view.js:29:15)
    at F:\hexo\node_modules\hexo\lib\hexo\index.js:349:21
    at tryCatcher (F:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at F:\hexo\node_modules\bluebird\js\release\method.

**Comment by zthxxx** [comment]
大概是主题的 _config.yml 配置没按格式来吧

[-> default_index_file | README](https://github.com/zthxxx/hexo-theme-Wikitten/blob/master/README_zh-CN.md#profilecommentshare-%E5%92%8C-miscellaneous-%E9%A1%B9%E9%83%BD%E6%98%AF-%E9%BB%98%E8%AE%A4%E5%85%B3%E9%97%AD%E7%9A%84)


![image](https://user-images.githubusercontent.com/15135943/64020286-d3601100-cb63-11e9-83c3-4b8f7276171a.png)

**Comment by ValueInvestmentChina** [comment]
谢谢，果然是没按文档来。
现在弄好的，不过问题是，没有左边分类的sidebar，这是我的地址https://valueinvestmentchina.github.io/，我就是超级喜欢这个分类清晰的sidebar，竟然没成功
所以想请教一下：
1.不知道是因为没有写文章进去，所以没有自动分类，还是因为config 没有设置好
2.我写文章到时候分类怎么写，全部按照文件夹建好放在hexo\source\categories里就可以了是吗

**Comment by zthxxx** [comment]
文章都是放在 `source/_posts` 下的，这是 hexo 的规范

sidebar 是靠文章分类生成的，

文章分类有两种，
一种是在文章 markdown 头部写 [front-matter](https://hexo.io/docs/front-matter)
一种是在  `source/_posts` 下面建文件夹，把文章文件放进去，默认会根据目录分类

**Comment by ValueInvestmentChina** [comment]
谢谢
差点放弃了，你的回答一阵见血，终于弄好了

**Comment by zthxxx** [comment]
前两天周末没看到。。

文章放 `source/_posts` 和 `front-matter` 都是 Hexo 官方做法，甚至都是各种博客系统的通用做法 🌝🌝

感谢使用反馈，没问题我就 close 了
