### ISSUE TITLE
侧边栏分类排序问题

### ISSUE THREAD

**Issue by ValueInvestmentChina** [zthxxx/hexo-theme-Wikitten#51]
不知道侧边框的排序是按照顺序什么来的，我的博文结构呈现出倒叙。

目录
-----李录
----------文章
---------------现代化十六讲
------------------------------ 2.第二讲
------------------------------ 1.第一讲
------------------------------ 0.序
1.md换过标题试过，不是标题原因。
2.找到里面的hexo下的list_categories，发现默认的name和升序（1），修改为降序（-1）测试也没有解决

**Comment by zthxxx** [comment]
默认官方插件是通过 markdown 文件名排序的，

之前的 issue 有说过，see #9

默认用的就是官方插件 [hexo-generator-index](https://github.com/hexojs/hexo-generator-index)， 可以配置其他排序方式

**Comment by ValueInvestmentChina** [comment]
抱歉，才回复，感谢，大神问题找打精准，以解决
