### ISSUE TITLE
Page布局的标题考虑加个上边距

### ISSUE THREAD

**Issue by Cardidi** [zthxxx/hexo-theme-Wikitten#52]
![image](https://user-images.githubusercontent.com/26651344/67148607-deb5fa00-f2d3-11e9-974f-2c4a1ec63dba.png)

总感觉连在一起的感觉很不爽。虽然我知道可以用post布局，但是主要我本人有强迫症，感觉首页不用page去掉顶端一行页面信息就是不爽😂。

**Comment by zthxxx** [comment]
```markdown
<br />

# 首页

xxxxx
```

**Comment by Cardidi** [comment]
好，谢谢了

**Comment by zthxxx** [comment]
还有直接用 front-matter 中的 title 是有边框的

直接写内容不推荐写 h1，也不能自动设置 title 属性
