### ISSUE TITLE
作者能否将font-awesome更新一下？

### ISSUE THREAD

**Issue by readlnh** [zthxxx/hexo-theme-Wikitten#53]
作者能否将font-awesome更新一下？我看到font-awesome还是很老的版本，更新了就可以用知乎微信之类的图标了

**Comment by zthxxx** [comment]
看了下新版，要升也就只能从现在 4.6.3  升到 4.7.0，

5.0 版开始大改了 svg 架构，接入要改动的地方太多，原类名 `fa` 也被抛弃，要重构的地方太多，暂时不考虑升到 5.0 版，

你看看 4.7 版对你有帮助么，有用的话 我就升到 4.7 版

https://fontawesome.com/v4.7.0/

**Comment by readlnh** [comment]
非常感谢，4.7也很有帮助，希望以后还能继续更新hhh真的非常好用

**Comment by zthxxx** [comment]
@readlnh  已更新，请拉最新代码试试
