### ISSUE TITLE
怎样让图片居左？

### ISSUE THREAD

**Issue by lovedva** [zthxxx/hexo-theme-Wikitten#59]
默认居中，我无论是用img style标签，还是表格里居左都不行，强行居中。
如果使用`<img src="...."  align="left">`就会这样把后面的所有内容给吞成一行
![image](https://user-images.githubusercontent.com/7524140/72999230-67e44c00-3e42-11ea-93a7-01c0e04393a4.png)

![image](https://user-images.githubusercontent.com/7524140/72999265-7894c200-3e42-11ea-96cf-fbd9d8a4b489.png)

跪求解。。。。

**Comment by zthxxx** [comment]
牢记 markdown 语法分割很多都靠换行 `\n\n` 而不是 `\n`

也就是说你少空了一行
