### ISSUE TITLE
希望支持markdown表格渲染

### ISSUE THREAD

**Issue by IcyW** [zthxxx/hexo-theme-Wikitten#60]
Markdown 制作表格使用 | 来分隔不同的单元格，使用 - 来分隔表头和其他行。

语法格式如下：

|  表头   | 表头  |
|  ----  | ----  |
| 单元格  | 单元格 |
| 单元格  | 单元格 |
https://www.runoob.com/markdown/md-table.html

这种格式在本主题中无法成功渲染为表格。

**Comment by IcyW** [comment]
sorry，是可以的。
在表格前多空一行即可解析成功。

**Comment by zthxxx** [comment]
牢记 markdown 语法分割很多都靠换行 `\n\n` 而不是 `\n`
