### ISSUE TITLE
文章目录找不到，显示空白

### ISSUE THREAD

**Issue by HappyClint** [zthxxx/hexo-theme-Wikitten#63]
如图：
![image](https://user-images.githubusercontent.com/23074032/80280032-f2836280-8733-11ea-969b-cdd0d2874726.png)

**Comment by zthxxx** [comment]
是不是没有开启 sideBar

**Comment by HappyClint** [comment]
Sidebar是插件吗，我第一次用hexo，不是很熟悉。用的是推荐的配置文件

**Comment by HappyClint** [comment]
> 是不是没有开启 sideBar
添加过这段代码，然后还是没有目录
![090D6D19-C44C-4652-9E02-F1412010852C](https://user-images.githubusercontent.com/23074032/80306914-93d3ec80-87f8-11ea-9da5-0213b03842af.jpeg)

**Comment by zthxxx** [comment]
麻烦发一下 截图(不是照片) & 博客地址 & 源码地址

**Comment by zthxxx** [comment]
@HappyClint  尝试更新 hexo-directory-category@^1.1.3

如没有问题的话这个 issuse 暂且关闭了
