### ISSUE TITLE
使用hexo切换主题的时候，wikitten.总是推送不上去。别的主题就可以。

### ISSUE THREAD

**Issue by shihunshi** [zthxxx/hexo-theme-Wikitten#65]
这个主题推送上去只有一个打不开的空文件夹

**Comment by zthxxx** [comment]
报错截图看看？

**Comment by shihunshi** [comment]
![image](https://user-images.githubusercontent.com/51902095/84678000-1019bf00-af62-11ea-814a-1dddfdfd7ffc.png)
![image](https://user-images.githubusercontent.com/51902095/84678065-26c01600-af62-11ea-8839-082fc337dda8.png)
一直提示是最新的，推送上去是空的，但是别的主题是没问题的。

**Comment by zthxxx** [comment]
看你截图里 GitHub 给出的图标说明你用的是 submodule 的方式，在 GitHub 看到就应该是这样没有问题，因为它就不是一个目录，是 submodule 的记录

另外请问你是否没有 git 或者前端的基础知识？

我看到你不仅没有 .gitmodules 还把几个 G 的 node_modules 全量传上来了。。。

![image](https://user-images.githubusercontent.com/15135943/84687551-81f90500-af70-11ea-88cd-381430215de4.png)
