### ISSUE TITLE
模仿搭建Wiki+Blog过程中产生的问题

### ISSUE THREAD

**Issue by stars-island** [zthxxx/hexo-theme-Wikitten#68]
按照博主的教程，照葫芦画瓢，想做一套Wiki+Blog的博客。Blog主题是Next7.8，Wiki的主题是博主提供的Wikitten。
遇到了一个问题，我也没办法用语言准确描述它，大概意思是我想要让Wikitten自己读取自己的post之类的东西，却读取到了NexT的post之类的东西，因为NexT主题里有些代码在Wikitten里是没有的。放上部署时候出现的错误的截图：
![image](https://user-images.githubusercontent.com/66160777/85205774-091ef200-b350-11ea-9ae0-f15571b843fe.png)
非常感谢！

**Comment by zthxxx** [comment]
建议把 blog 和 wiki 放成两个 hexo 项目和 git 仓库，

同一个仓库里同时使用两个 hexo 主题是错误的用法，他们应该分开放分开部署，

当你想在 blog 中关联 wiki 时，可以直接放上 wiki 的地址，比如在 blog 页面顶部 header 中

**Comment by stars-island** [comment]
非常感谢您的回复！

我在github网站上确实是分开两个repository：

![image](https://user-images.githubusercontent.com/66160777/85214232-f54cad80-b39a-11ea-806b-59efcd19a738.png)

站点配置文件做成_config.next.yml和_config.Wikitten.yml，在deploy的时候，分别写出两条命令如下：

```
hexo g -d --config _config.next.yml

hexo g -d --config _config.Wikitten.yml

```

今早起床的时候调整了思路，把_config.Wikitten.yml里的设置改写一下：

```
# Directory
source_dir: _source
public_dir: _public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
  - README.md
  - '_posts/**/embed_page/**'
```

在文件夹里长成这样子：

![image](https://user-images.githubusercontent.com/66160777/85214174-69d31c80-b39a-11ea-9aef-745b6e7dbf44.png)

选中的三个文件夹是另外新建的文件夹，我个人认为这个做法可以避免两个主题的posts混在一起。刚才打开网页测试，暂时没有发现问题。

可能这样不太符合您给出的建议吧？接下来我去尝试在hexo下新建一个wiki文件夹，像这样：

![image](https://user-images.githubusercontent.com/66160777/85214662-912ce800-b3a0-11ea-9fbc-64d228f092b7.png)

我想这个或许才是您建议的做法。

谢谢！

**Comment by stars-island** [comment]
刚才完全遵循您的建议，也是可行的，而且分开两个git仓库，感觉比我原来的想法更加清晰，文件夹里的东西不会混乱。非常感谢！

**Comment by zthxxx** [comment]
很棒
