### ISSUE TITLE
如何修改站点的语言设置？

### ISSUE THREAD

**Issue by rosuH** [zthxxx/hexo-theme-Wikitten#7]
Hexo 的站点配置文件中有一项为`language`的属性。但是我不知道具体的属性值。

请问这个属性值是否是因所用主题变化而改变的？我使用了
```
language: zh-cn
```
这样的属性值是否是无效的？如果我要设置界面为英文呢？

-----
谢谢

**Comment by zthxxx** [comment]
@rosuH  是有效的，就是这样设置没错。

Hexo 官方文档中设置语言就是这样的。

https://hexo.io/zh-cn/docs/internationalization.html

语言翻译项对应设置在 `/themes/Wikitten/languages/` 下的文件中。
