### ISSUE TITLE
一个自用的脚本

### ISSUE THREAD

**Issue by Pengyang233** [zthxxx/hexo-theme-Wikitten#71]
谢谢  @zthxxx 提供的模板和耐心的解答，我非常喜欢这个模板。
为了记笔记的时候能够更舒服，我抽时间写了一个脚本，这个脚本是我参照另一位博主的思路写的，能够实现在另一个组织更加整洁的文件夹下写笔记，随后使用该脚本同步到 hexo 源代码文件夹下。结合 Github Action，能够尽可能地节约重复地工作。
脚本地址：https://github.com/Pengyang233/scripts/tree/master/script%20for%20hexo
里面有一些功能并不是很完善，不过都够用了。

**Comment by zthxxx** [comment]
👍
