### ISSUE TITLE
[BUG]无序列表有错误

### ISSUE THREAD

**Issue by guohoo** [zthxxx/hexo-theme-Wikitten#75]
# 出错的文本：
```
## 参数
- expression —— 表达式。 
- globals —— 变量作用域，全局命名空间，如果被提供，则必须是一个字典对象。 
- locals —— 变量作用域，局部命名空间，如果被提供，可以是任何映射对象。
```

# 预期效果：
## 参数
- expression —— 表达式。 
- globals —— 变量作用域，全局命名空间，如果被提供，则必须是一个字典对象。 
- locals —— 变量作用域，局部命名空间，如果被提供，可以是任何映射对象。

# 实际渲染后的效果：
## 参数
expression —— 表达式。 
- globals —— 变量作用域，全局命名空间，如果被提供，则必须是一个字典对象。 
- locals —— 变量作用域，局部命名空间，如果被提供，可以是任何映射对象。

# F12检查：
```
<ul>
    <li class="task-list check">expression —— 表达式。 </li>
    <li>globals —— 变量作用域，全局命名空间，如果被提供，则必须是一个字典对象。 </li>
    <li>locals —— 变量作用域，局部命名空间，如果被提供，可以是任何映射对象。 </li>
</ul>
```
不清楚什么原因，直接在`md`文件里用如下`html`标签还是这样
```
<ul>
    <li>expression —— 表达式。 </li>
    <li>globals —— 变量作用域，全局命名空间，如果被提供，则必须是一个字典对象。 </li>
    <li>locals —— 变量作用域，局部命名空间，如果被提供，可以是任何映射对象。 </li>
</ul>
```

**Comment by guohoo** [comment]
补充测试结果：
```
- oox
- xox
- oxo
- x11
- x
- xp 
- e
```

效果：
- oox
xox
oxo
x11
x
xp
- e

貌似列表里只要在最后一个字母前有`x`就会触发

**Comment by zthxxx** [comment]
@guohoo  感谢反馈，在 5b0d493 中已修复，请再更新主题试试
